# Generated by Django 5.2.8 on 2025-12-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_url_alter_book_external_id_and_more'),
        ('custom_lists', '0001_initial'),
        ('films', '0002_film_actors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customlistitem',
            unique_together={('custom_list', 'content_type', 'book', 'film')},
        ),
    ]
