# Generated by Django 5.2.8 on 2025-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
