# Generated by Django 5.2.8 on 2025-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
